### ISSUE TITLE
Why not using onion messages?

### ISSUE THREAD

**Issue by renepickhardt** [GeorgeTsagk/satoshi-read-write#6]
Just curious I think Onion Messages can be used to partially achieve this. Wouldn't it make more sense to build on top of them? c.f: https://github.com/lightning/bolts/pull/759

**Comment by GeorgeTsagk** [comment]
I suppose yes, but there's something about the proposed onion messaging that I don't get:

After reading the changes it was quite unclear if they use the existing payment flow by attaching the onion message to a payment's HTLC (as a custom record for the final hop), or if they just use the same onion routing model for dry message forwarding.

If the first one is the case, then I don't see why there needs to be a new BOLT about it, as this is something supported already (and also demonstrated in this app).

If it's the second case (dry forwards) then I don't see why would the network opt-in to this as there is no compensation for forwarding messages to other nodes. Bandwidth is a resource and should be treated like one.

I believe something to keep from the proposal is blinded routes for responding to an anonymous message sender. Apart from that, I believe using payments to carry data towards a destination is an already existing rail that:
- Does not require a new BOLT
- Has built-in compensation for routing nodes (the base fee of the channel over which the message is forwarded)

**Comment by renepickhardt** [comment]
yes onion messages just use the same routing model for dry message forwarding. I think bandwidth is less expensive than commiting HTLCs and storing revocation keys for ever in old channel state. Thus I think in the current proposal onion messages are free but probably rate limited. I guess that philosophic debate about onion messages and how economical they are should be moved to the PR in the bolts repo?

**Comment by GeorgeTsagk** [comment]
Yes certainly. I believe there is room for improvements as far as storage goes for node implementations.

I agree this conversation should be moved there.
